### ISSUE TITLE
Library evaluation tracking issue

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/lazy-static.rs#70]
- [x] [Publish CI badges for all Tier 1 platforms](https://github.com/rust-lang-nursery/lazy-static.rs/issues/65)
- [x] [Include `categories` in Cargo.toml](https://github.com/rust-lang-nursery/lazy-static.rs/issues/66)
- [x] [Include `homepage` in Cargo.toml](https://github.com/rust-lang-nursery/lazy-static.rs/issues/67)
- [x] [Change Cargo.toml `documentation`](https://github.com/rust-lang-nursery/lazy-static.rs/issues/68)
- [x] [Set html_root_url crate attribute](https://github.com/rust-lang-nursery/lazy-static.rs/issues/69)
- [ ] ~~[Consider changing syntax / name](https://github.com/rust-lang-nursery/lazy-static.rs/issues/73)~~
- [x] Bump version to 1.0 (after all else)

This is the tracking issue for the [evaluation](https://public.etherpad-mozilla.org/p/rust-crate-eval-lazy-static) performed by the libs team last week.

**Comment by dtolnay** [comment]
@Kimundi do you consider any of the other issues filed so far to be blockers for 1.0?

**Comment by Kimundi** [comment]
@dtolnay: No blockers in the existing issues, but I've opened #73 which is something I wanted to address before 1.0.

**Comment by brson** [comment]
I added https://github.com/rust-lang-nursery/lazy-static.rs/issues/73 to the op.

**Comment by Kimundi** [comment]
As per https://github.com/rust-lang-nursery/lazy-static.rs/issues/73#issuecomment-342787981, I've decided to postpone #73 for the 1.0 release.
